import Head from "next/head";
// import Hero from "../components/hero";
import { motion as m } from "framer-motion";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Spotify Shop Survey</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-3xl mx-auto h-screen w-full flex">
        {/* Welcome page */}
        <div className="bg-[#222222] w-full h-3/6 text-white rounded-xl shadow shadow-gray-800 mt-28">
          {/* Page title */}
          <p className="font-bold text-center capitalize text-4xl mt-20">
            welcome to spotify shop
          </p>

          {/* Demo button */}
          <Link href="/demo">
            <m.div
              whileHover={{ scale: 1.2 }}
              whileTap={{ scale: 0.9 }}
              transition={{ type: "spring", stiffness: 400, damping: 17 }}
              className="flex justify-center mt-10 h-16 items-center cursor-pointer"
            >
              {/* <a href="https://www.figma.com/proto/qxCMtdK7IJOReyugbRKeGT/Spotify?node-id=169%3A2448&starting-point-node-id=169%3A2448&scaling=scale-down"> */}
              <div className="w-40 h-12 flex items-center justify-center rounded-full bg-[#1DB954] shadow-lg">
                <p className="text-black text-sm font-bold capitalize">
                  View the demo
                </p>
              </div>
              {/* </a> */}
            </m.div>
          </Link>

          {/* Survey */}
        </div>
      </div>
    </div>
  );
}
